### ISSUE TITLE
调用publish会间歇性的出错

### ISSUE THREAD

**Issue by liubaishui** [bearyinnovative/jenkins-bearychat-plugin#13]
```
Posting: to DEV-MOBILE on xxx using https://xxx.bearychat.com/api/hooks/jenkins/TOKENSTRING: {color=#FF0000, message=STARTED Build Lua scripts: Job 'JENKINS_JOBNAME [159]' (https://jenkins/job/JENKINS_JOBNAME/159/)}
三月 05, 2017 4:09:40 下午 警告 jenkins.plugins.bearychat.StandardBearychatService publish
Error posting to BearyChat
java.io.IOException: Stream closed
	at java.io.BufferedInputStream.getBufIfOpen(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at org.apache.commons.httpclient.ContentLengthInputStream.read(ContentLengthInputStream.java:170)
	at java.io.FilterInputStream.read(Unknown Source)
	at org.apache.commons.httpclient.AutoCloseInputStream.read(AutoCloseInputStream.java:108)
	at java.io.FilterInputStream.read(Unknown Source)
	at org.apache.commons.httpclient.AutoCloseInputStream.read(AutoCloseInputStream.java:127)
	at org.apache.commons.httpclient.HttpMethodBase.getResponseBody(HttpMethodBase.java:690)
	at org.apache.commons.httpclient.HttpMethodBase.getResponseBodyAsString(HttpMethodBase.java:803)
	at jenkins.plugins.bearychat.StandardBearychatService.publish(StandardBearychatService.java:113)
	at jenkins.plugins.bearychat.StandardBearychatService.publish(StandardBearychatService.java:49)
	at jenkins.plugins.bearychat.StandardBearychatService.publish(StandardBearychatService.java:42)
	at jenkins.plugins.bearychat.workflow.BearychatSendStep$BearychatSendStepExecution.run(BearychatSendStep.java:201)
	at jenkins.plugins.bearychat.workflow.BearychatSendStep$BearychatSendStepExecution.run(BearychatSendStep.java:159)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:52)
	at hudson.security.ACL.impersonate(ACL.java:260)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:49)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

在发送的时候间歇性会出现 java.io.IOException: Stream closed 异常。

**Comment by bcho** [comment]
Hi, 请问你这边 jenkins 部署的网络是怎样的？这种情况可能是 jenkins 所在的网络到 bearychat 这边的网络有点问题

**Comment by liubaishui** [comment]
Jenkins在公司的内网，通过NAT出去的，网络质量是很稳定的。

**Comment by liubaishui** [comment]
而且我们同时有在用JIRA和GITLAB的webhook，没有出现过类似情形。

**Comment by yuanbohan** [comment]
我们团队在大量使用 BearyChat Jenkins 插件, 没有发生过这个问题. 使用本插件的用户也没有反馈过这个问题. 我们暂时将这个问题定为网络问题, 我们会近期跟踪并尝试重现一下这个问题. 感谢 @liubaishui 的反馈
